podman-compose: remove pypi inherit to fix do_fetch
* now when pypi uses SRC_URI_prepend since:
  https://git.openembedded.org/openembedded-core/commit/?id=8f17b8bce85efb0e9a7e15d0b98a5cf7b6bd9750
  both entries end in SRC_URI (because of delayed nature of prepend):
  https://files.pythonhosted.org/packages/source/p/podman-compose/podman-compose-0.1.5.tar.gz
  git://github.com/containers/podman-compose.git

  causing:
  ERROR: podman-compose-0.1.5-r0 do_fetch: No checksum specified for '/OE/build/oe-core/downloads/podman-compose-0.1.5.tar.gz', please add at least one to the recipe:
  SRC_URI[sha256sum] = "fb229362f188980ea3fbdee2a25d0a2dd6a0b886d925d5213e22e09f1062ebe9"
  ERROR: podman-compose-0.1.5-r0 do_fetch: Fetcher failure for URL: 'https://files.pythonhosted.org/packages/source/p/podman-compose/podman-compose-0.1.5.tar.gz'. Missing SRC_URI checksum
  ERROR: Logfile of failure stored in: /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/podman-compose/0.1.5-r0/temp/log.do_fetch.55855

  drop pypi inherit to restore the previous SRC_URI with just the git:// entry.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
(cherry picked from commit 92f976404b7f82c97996ffce94ca2d20be2dcbda)